# v2 syntax
version: '2'

# Named volumes
volumes:
  # Elastic Search Data
  jarvishub-elastic-data:
    driver: local

  # Redis Data
  jarvishub-redis-data:
    driver: local

services:
  # ELASTIC SEARCH
  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.3.1
    container_name: jarvishub-elastic
    volumes:
      - jarvishub-elastic-data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"

  # REDIS
  cache:
    image: redis:4.0
    container_name: jarvishub-redis
    command: --appendonly yes
    volumes:
      - jarvishub-redis-data:/data
    ports:
      - "6378:6379"
